#include <iostream>
using namespace std;

//Tabla de multplicación del numero entero que coloque el usuario

int main()
{
     int a, b;
    cout << "Ingresa un numero del 0 al 9" <<endl;
    cin >> a;

     if(a<=a) {
     a;
     }
     else if (a>=9){
     a;
     }
     else

    cout <<"El resultado del multiplo por uno es: "<< a*1 <<endl;
    cout <<"El resultado del multiplo por dos es: "<< a*2 <<endl;
    cout <<"El resultado del multiplo por tres es: "<< a*3 <<endl;
    cout <<"El resultado del multiplo por cuatro es: "<< a*4 <<endl;
    cout <<"El resultado del multiplo por cinco es: "<< a*5 <<endl;
    cout <<"El resultado del multiplo por seis es: "<< a*6 <<endl;
    cout <<"El resultado del multiplo por siete es: "<< a*7 <<endl;
    cout <<"El resultado del multiplo por ocho es: "<< a*8 <<endl;
    cout <<"El resultado del multiplo por nueve es: "<< a*9 <<endl;
    cout <<"El resultado del multiplo por cero es: "<< a*0 <<endl;

 system("pause");
 return EXIT_SUCCESS;
}